"use client";

import { useTranslations } from "next-intl";

const reviewStyles = [
  { initial: "D", avatarColor: "#5f6368" },
  { initial: "A", avatarColor: "#1a73e8" },
  { initial: "M", avatarColor: "#e8710a" },
] as const;

export function useCallUsCopy() {
  const t = useTranslations("offers.callUs");

  return {
    callNow: t("callNow"),
    callAriaLabel: t("callAriaLabel"),
    brandHomeAriaLabel: t("brandHomeAriaLabel"),
    brandLogoAlt: t("brandLogoAlt"),
    heroHeading: t("heroHeading"),
    heroSubtitle: t("heroSubtitle"),
    heroDescription: t("heroDescription"),
    heroNote: t("heroNote"),
    heroImageAlt: t("heroImageAlt"),
    googleTrustAriaLabel: t("googleTrustAriaLabel"),
    googleTrustBadgeLabel: t("googleTrustBadgeLabel"),
    googleTrustRatingAriaLabel: t("googleTrustRatingAriaLabel"),
    googleTrustReviewCount: t("googleTrustReviewCount"),
    formSectionAriaLabel: t("formSectionAriaLabel"),
    formNameLabel: t("formNameLabel"),
    formPhoneLabel: t("formPhoneLabel"),
    formSummaryLabel: t("formSummaryLabel"),
    formSummaryOptional: t("formSummaryOptional"),
    formSummaryPlaceholder: t("formSummaryPlaceholder"),
    formPhoneTitle: t("formPhoneTitle"),
    formSubmitLoading: t("formSubmitLoading"),
    formSubmitIdle: t("formSubmitIdle"),
    formPrivacyNote: t("formPrivacyNote"),
    formError: t("formError"),
    reviewsEyebrow: t("reviewsEyebrow"),
    reviewsHeading: t("reviewsHeading"),
    reviewsGoogleLink: t("reviewsGoogleLink"),
    reviewStarsAriaLabel: t("reviewStarsAriaLabel"),
    googleReviews: reviewStyles.map((style, index) => ({
      ...style,
      name: t(`googleReviews.${index}.name`),
      meta: t(`googleReviews.${index}.meta`),
      date: t(`googleReviews.${index}.date`),
      text: t(`googleReviews.${index}.text`),
    })),
    servicesEyebrow: t("servicesEyebrow"),
    servicesHeading: t("servicesHeading"),
    services: t.raw("services") as string[],
    bookAppointment: t("bookAppointment"),
    aboutHeading: t("aboutHeading"),
    aboutEyebrow: t("aboutEyebrow"),
    doctorImageAlt: t("doctorImageAlt"),
    doctorCredential: t("doctorCredential"),
    doctorBio: t("doctorBio"),
    insuranceEyebrow: t("insuranceEyebrow"),
    insuranceHeading: t("insuranceHeading"),
    insuranceIntro: t("insuranceIntro"),
    insuranceImageAlt: t("insuranceImageAlt"),
    offer99Description: t("offer99Description"),
    offer59Description: t("offer59Description"),
    finalEyebrow: t("finalEyebrow"),
    finalHeading: t("finalHeading"),
    finalDescription: t("finalDescription"),
    requestCallbackInstead: t("requestCallbackInstead"),
    footerLocationLabel: t("footerLocationLabel"),
    footerOfficeHours: t("footerOfficeHours"),
    emergencyCasesOnly: t("emergencyCasesOnly"),
    officeHours: t.raw("officeHours") as { day: string; hours: string; note?: string }[],
    thankYouKicker: t("thankYouKicker"),
    thankYouTitle: t("thankYouTitle"),
    thankYouReceived: t("thankYouReceived"),
    thankYouFollowUp: t("thankYouFollowUp"),
    thankYouBackToOffers: t("thankYouBackToOffers"),
    thankYouBackToHome: t("thankYouBackToHome"),
  };
}
